apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: quarked
  name: quarked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarked
  template:
    metadata:
      labels:
        app: quarked
    spec:
      containers:
      - name: quarked
        image: dev.local/burrsutter/quarked:1.0.0
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "300Mi" 
            cpu: "250m" # 1/4 core
          limits:
            memory: "400Mi"
            cpu: "1000m" # 1 core
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

