apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: noded
  name: noded
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noded
  template:
    metadata:
      labels:
        app: noded
    spec:
      containers:
      - name: noded
        image: quay.io/burrsutter/noded:1.0.1
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "300Mi" 
            cpu: "250m" # 1/4 core
          limits:
            memory: "400Mi"
            cpu: "1000m" # 1 core
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

